MarketPic:
  follow_line: /Resources/AuctionMarket/my_follow_page.png
  main_line: /Resources/AuctionMarket/main_line_v2.png
  ok: /Resources/AuctionMarket/ok.png
  plus_price: /Resources/AuctionMarket/plus_10.png
  plus_price_100: /Resources/AuctionMarket/plus_100.png
  summit_price: /Resources/AuctionMarket/summit.png
TruckCarFindTask:
  Area:
    JinLing:
      HuangJiaLieChang: /Resources/TruckCarFindTask/Area/JinLing/皇家猎场.png
      MeiHuaMen: /Resources/TruckCarFindTask/Area/JinLing/梅花门.png
      MoChouHu: /Resources/TruckCarFindTask/Area/JinLing/莫愁湖.png
      address: /Resources/TruckCarFindTask/NPC/金陵.png
      npc: /Resources/TruckCarFindTask/NPC/金陵npc.png
    LuoYang:
      BaoDuZhai: /Resources/TruckCarFindTask/Area/LuoYang/抱犊寨.png
      QinWangFu: /Resources/TruckCarFindTask/Area/LuoYang/秦王府.png
      YanMenShiJia: /Resources/TruckCarFindTask/Area/LuoYang/燕门世家.png
      address: /Resources/TruckCarFindTask/NPC/洛阳.png
      npc: /Resources/TruckCarFindTask/NPC/洛阳npc.png
    SuZhou:
      BaoChuanChang: /Resources/TruckCarFindTask/Area/SuZhou/宝船厂.png
      CaiShiChang: /Resources/TruckCarFindTask/Area/SuZhou/采石场.png
      WuWangMu: /Resources/TruckCarFindTask/Area/SuZhou/吴王墓.png
      YongCuiShanZhuang: /Resources/TruckCarFindTask/Area/SuZhou/拥翠山庄.png
      address: /Resources/TruckCarFindTask/NPC/苏州.png
      npc: /Resources/TruckCarFindTask/NPC/苏州npc.png
    YanJin:
      DongFang: /Resources/TruckCarFindTask/Area/YanJin/东方世家.png
      JiMingYi: /Resources/TruckCarFindTask/Area/YanJin/鸡鸣驿.png
      JunMaChang: /Resources/TruckCarFindTask/Area/YanJin/军马场.png
      YiRenZhuang: /Resources/TruckCarFindTask/Area/YanJin/异人庄.png
      address: /Resources/TruckCarFindTask/NPC/燕京.png
      npc: /Resources/TruckCarFindTask/NPC/燕京npc.png
    chengdu:
      GaiBang: /Resources/TruckCarFindTask/Area/ChengDu/丐帮驻地.png
      NanGong: /Resources/TruckCarFindTask/Area/ChengDu/南宫世家.png
      QianDengZheng: /Resources/TruckCarFindTask/Area/ChengDu/千灯镇.png
      ShenJiaBao: /Resources/TruckCarFindTask/Area/ChengDu/沈家堡.png
      address: /Resources/TruckCarFindTask/NPC/成都.png
      npc: /Resources/TruckCarFindTask/NPC/成都npc.png
  car_type_big: /Resources/TruckCarFindTask/CarType/大车.png
  car_type_little: /Resources/TruckCarFindTask/CarType/小车.png
  car_type_medium: /Resources/TruckCarFindTask/CarType/中车.png
  qin_xiu: /Resources/TruckCarFindTask/勤修.png
  bang_hui: /Resources/TruckCarFindTask/帮会.png
  qin_xiu_activity_list: /Resources/TruckCarFindTask/活动列表.png
  qin_xiu_truck_car_npc_chengdu: /Resources/TruckCarFindTask/chengdu_truck_car_npc.png
  qin_xiu_truck_car_task: /Resources/TruckCarFindTask/日常运镖.png
  receive_task: /Resources/TruckCarFindTask/receive_task.png
  receive_task_confirm: /Resources/TruckCarFindTask/receive_task_confirm.png
  receive_task_talk: /Resources/TruckCarFindTask/receive_task_talk.png
  break_npc_talk: /Resources/TruckCarFindTask/break_talk.png
TruckCarPic:
  car_flag: /Resources/TruckCarPic/CarsFlag.png
  task_car_selected: /Resources/TruckCarPic/truck_car_selected.png
  task_flag_status: /Resources/TruckCarPic/CarFlag.png
  task_flags_yellow_car: /Resources/TruckCarPic/car_yellow_flag.png
  task_monster_fight: /Resources/TruckCarPic/fight_status_2.png
  task_monster_target: /Resources/TruckCarPic/fight_status_2.png
  task_monster_target_skill: /Resources/TruckCarPic/car_monster_skill_1.png
  task_star_mode: /Resources/TruckCarPic/truck_type.png
  fight_other_truck_car: /Resources/TruckCarPic/镖车切磋.png
MapPic:
  pos_x: /Resources/Map/pox_x.png
  pos_y: /Resources/Map/pox_y.png
  search_pos: /Resources/Map/search_pos.png
  result_point: /Resources/Map/result_point.png
  plus_map: /Resources/Map/plus_map.png
danceConfig:
  dance_threshold_area: 0.3
  dance_threshold_tl: 0.9
  dance_threshold_whz: 0.8
  debug: false
  truck_car_max_sum: 5
dancePic:
  tlDancePic:
    button_down: /Resources/DancePic/down.png
    button_find_area: /Resources/DancePic/find_dance_area.png
    button_find_area_night: /Resources/DancePic/find_dance_area_night.png
    button_j: /Resources/DancePic/J.png
    button_k: /Resources/DancePic/K.png
    button_l: /Resources/DancePic/L.png
    button_left: /Resources/DancePic/left.png
    button_right: /Resources/DancePic/right.png
    button_up: /Resources/DancePic/up.png
  whzDancePic:
    button_down: /Resources/DancePic/whzDance_Down.png
    button_find_area: /Resources/DancePic/find_whz_area.png
    button_left: /Resources/DancePic/whzDance_left.png
    button_right: /Resources/DancePic/whzDance_right.png
    button_up: /Resources/DancePic/whzDance_UP.png
goods:
  goods_bag_tag_clickable: /Resources/Goods/物品包02.png
  goods_bag_tag_clicked: /Resources/Goods/物品包01.png
  run_goods: /Resources/Goods/御风神水.png
  run_goods_buff: /Resources/Goods/御风神水buff.png
  run_goods_ready: /Resources/Goods/御风神水ready.png
  non_blood: /Resources/Goods/满血.png
  sit_blood: /Resources/Goods/打坐.png
keyBoardMouseDll:
  dmDll:
    dm: /Resources/KeyBoardDriver/dm.dll
    dm_reg: /Resources/KeyBoardDriver/DmReg.dll
  ghostDll:
    ghost_dll: /Resources/KeyBoardDriver/gbild64.dll
team:
  create_team: /Resources/Team/创建队伍.png
  flag_team: /Resources/Team/team_mark.png
  flag_team_status: /Resources/Team/队伍标志.png
  leave_team: /Resources/Team/解散队伍.png
