TruckCarFindTask:
  qin_xiu: ./DeskPageV2/Resources/TruckCarFindTask/勤修.png
  qin_xiu_activity_list : ./DeskPageV2/Resources/TruckCarFindTask/活动列表.png
  qin_xiu_truck_car_npc_chengdu: ./DeskPageV2/Resources/TruckCarFindTask/chengdu_truck_car_npc.png
  qin_xiu_truck_car_task: ./DeskPageV2/Resources/TruckCarFindTask/日常运镖.png
  car_type_big: ./DeskPageV2/Resources/TruckCarFindTask/CarType/大车.png
  car_type_little: ./DeskPageV2/Resources/TruckCarFindTask/CarType/小车.png
  car_type_medium: ./DeskPageV2/Resources/TruckCarFindTask/CarType/中车.png
  receive_task: ./DeskPageV2/Resources/TruckCarFindTask/receive_task.png
  receive_task_confirm: ./DeskPageV2/Resources/TruckCarFindTask/receive_task_confirm.png
  receive_task_talk: ./DeskPageV2/Resources/TruckCarFindTask/receive_task_talk.png
  Area:
    chengdu:
      address: ./DeskPageV2/Resources/TruckCarFindTask/NPC/成都.png
      npc: ./DeskPageV2/Resources/TruckCarFindTask/NPC/成都npc.png
      GaiBang: ./DeskPageV2/Resources/TruckCarFindTask/Area/ChengDu/丐帮驻地.png
      NanGong: ./DeskPageV2/Resources/TruckCarPic/Area/ChengDu/南宫世家.png
      QianDengZheng: ./DeskPageV2/Resources/TruckCarFindTask/Area/ChengDu/千灯镇.png
      ShenJiaBao: ./DeskPageV2/Resources/TruckCarFindTask/Area/ChengDu/沈家堡.png
    JinLing:
      address: ./DeskPageV2/Resources/TruckCarFindTask/NPC/金陵.png
      npc: ./DeskPageV2/Resources/TruckCarFindTask/NPC/金陵npc.png
    LuoYang:
      address: ./DeskPageV2/Resources/TruckCarFindTask/NPC/洛阳.png
      npc: ./DeskPageV2/Resources/TruckCarFindTask/NPC/洛阳npc.png
    SuZhou:
      address: ./DeskPageV2/Resources/TruckCarFindTask/NPC/苏州.png
      npc: ./DeskPageV2/Resources/TruckCarFindTask/NPC/苏州npc.png
    YanJin:
      address: ./DeskPageV2/Resources/TruckCarFindTask/NPC/燕京.png
      npc: ./DeskPageV2/Resources/TruckCarFindTask/NPC/燕京npc.png
      DongFang: ./DeskPageV2/Resources/TruckCarFindTask/Area/YanJin/东方世家.png
      JiMingYi: ./DeskPageV2/Resources/TruckCarFindTask/Area/YanJin/鸡鸣驿.png
      JunMaChang: ./DeskPageV2/Resources/TruckCarFindTask/Area/YanJin/军马场.png
      YiRenZhuang: ./DeskPageV2/Resources/TruckCarFindTask/Area/YanJin/异人庄.png
TruckCarPic:
  car_flag: ./DeskPageV2/Resources/TruckCarPic/CarsFlag.png
  task_flag_status: ./DeskPageV2/Resources/TruckCarPic/CarFlag.png
  task_flags_yellow_car: ./DeskPageV2/Resources/TruckCarPic/car_yellow_flag.png
  task_monster_fight: ./DeskPageV2/Resources/TruckCarPic/fight_status.png
  task_monster_target:
  - ./DeskPageV2/Resources/TruckCarPic/car_monster.png
  - ./DeskPageV2/Resources/TruckCarPic/car_monster2.png
  - ./DeskPageV2/Resources/TruckCarPic/car_monster3.png
  task_star_mode: ./DeskPageV2/Resources/TruckCarPic/truck_type.png
  task_car_selected: ./DeskPageV2/Resources/TruckCarPic/truck_car_selected.png
config:
  dance_threshold_area: 0.3
  dance_threshold_tl: 0.9
  dance_threshold_whz: 0.8
  debug: false
dancePic:
  tlDancePic:
    button_down: /Resources/DancePic/down.png
    button_find_area: /Resources/DancePic/find_dance_area.png
    button_find_area_night: /Resources/DancePic/find_dance_area_night.png
    button_j: /Resources/DancePic/J.png
    button_k: /Resources/DancePic/K.png
    button_l: /Resources/DancePic/L.png
    button_left: /Resources/DancePic/left.png
    button_right: /Resources/DancePic/right.png
    button_up: /Resources/DancePic/up.png
  whzDancePic:
    button_down: /Resources/DancePic/whzDance_Down.png
    button_find_area: /Resources/DancePic/find_whz_area.png
    button_left: /Resources/DancePic/whzDance_left.png
    button_right: /Resources/DancePic/whzDance_right.png
    button_up: /Resources/DancePic/whzDance_UP.png
keyBoardMouseDll:
  dmDll:
    dm: /Resources/KeyBoardDriver/dm.dll
    dm_reg: /Resources/KeyBoardDriver/DmReg.dll
  ghostDll:
    ghost_dll: /Resources/KeyBoardDriver/gbild64.dll
team:
  create_team: ./DeskPageV2/Resources/Team/创建队伍.png
  flag_team: ./DeskPageV2/Resources/Team/team_mark.png
  flag_team_status: ./DeskPageV2/Resources/Team/队伍标志.png
  leave_team: ./DeskPageV2/Resources/Team/离开队伍.png
